[package]
name = "multi-bucket"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashlink = "0.8.4"
thiserror = "1.0.50"
